import { StyleSheet } from "react-native";

export const colors = {
  red: "#ff311f",
  orange: "#ff6b21",
  dark: "#7a0d05",
  ink: "#111827",
  muted: "#6d7c94",
  line: "#e5edf7",
  bg: "#f8fbff",
  green: "#10a85b"
};

export const styles = StyleSheet.create({
  appShell: { flex: 1, backgroundColor: colors.bg },
  screen: { flex: 1, backgroundColor: colors.bg },
  center: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24 },
  content: { flex: 1, marginTop: -18, borderTopLeftRadius: 20, borderTopRightRadius: 20, backgroundColor: colors.bg, paddingTop: 14 },
  list: { padding: 14, gap: 12, paddingBottom: 96 },
  emptyList: { flexGrow: 1, alignItems: "center", justifyContent: "center", padding: 24 },

  brandBlock: { alignItems: "center" },
  brandText: { fontSize: 34, fontWeight: "900", color: colors.ink, lineHeight: 38 },
  brandCompact: { fontSize: 22, fontWeight: "900", color: "#fff", lineHeight: 24 },
  brandLight: { color: "#fff" },
  brandAccent: { color: colors.red },
  brandRider: { marginTop: -4, color: colors.ink, fontSize: 17, fontWeight: "900" },
  brandRiderLight: { color: "#fff" },

  logoMark: { alignItems: "center", justifyContent: "center", backgroundColor: colors.red },
  logoGV: { position: "absolute", bottom: 13, color: "#fff", fontSize: 12, fontWeight: "900" },

  waveHeader: { minHeight: 150, backgroundColor: colors.dark, paddingTop: 28, alignItems: "center", justifyContent: "center", overflow: "hidden" },
  headerGlowA: { position: "absolute", width: 180, height: 180, borderRadius: 90, backgroundColor: colors.red, left: -70, bottom: -110 },
  headerGlowB: { position: "absolute", width: 150, height: 150, borderRadius: 75, backgroundColor: colors.orange, right: -60, top: -60 },
  topBar: { minHeight: 74, paddingTop: 18, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: colors.dark },
  topBarLeft: { flexDirection: "row", alignItems: "center", gap: 8 },
  topIcon: { width: 36, height: 36, alignItems: "center", justifyContent: "center" },
  topTitle: { color: "#fff", fontSize: 20, fontWeight: "900" },

  button: { minHeight: 54, borderRadius: 8, paddingHorizontal: 18, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8 },
  hotButton: { backgroundColor: colors.red },
  outlineButton: { backgroundColor: "#fff", borderWidth: 1.5, borderColor: colors.red },
  buttonText: { color: "#fff", fontSize: 16, fontWeight: "900" },
  outlineText: { color: colors.red },
  disabled: { opacity: 0.55 },
  pressed: { opacity: 0.78 },

  pillTabs: { marginHorizontal: 14, padding: 5, borderRadius: 8, backgroundColor: "#edf2f9", flexDirection: "row", gap: 5 },
  pillTab: { flex: 1, minHeight: 38, borderRadius: 8, alignItems: "center", justifyContent: "center", paddingHorizontal: 6 },
  pillTabActive: { backgroundColor: colors.red },
  pillText: { color: "#40506b", fontSize: 12, fontWeight: "800", textAlign: "center" },
  pillTextActive: { color: "#fff" },

  emptyState: { alignItems: "center", gap: 8 },
  emptyTitle: { fontSize: 20, fontWeight: "900", color: colors.ink },
  emptyCopy: { color: colors.muted, textAlign: "center", fontWeight: "600" },

  foodThumb: { width: 72, height: 72, borderRadius: 8, backgroundColor: "#d9391e", alignItems: "center", justifyContent: "center", overflow: "hidden" },
  foodImage: { width: "100%", height: "100%" },
  rowBetween: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  flex1: { flex: 1 },
  smallMuted: { color: colors.muted, fontSize: 12, fontWeight: "600" },
  redSmall: { color: colors.red, fontSize: 12, fontWeight: "800" },
  greenText: { color: colors.green, fontSize: 12, fontWeight: "900" },
  greenStrong: { color: colors.green, fontSize: 15, fontWeight: "900" },

  orderCard: { borderRadius: 8, borderWidth: 1, borderColor: colors.line, backgroundColor: "#fff", padding: 10, flexDirection: "row", gap: 12, shadowColor: "#0f172a", shadowOpacity: 0.06, shadowRadius: 10, elevation: 2 },
  orderInfo: { flex: 1, gap: 4 },
  orderCode: { color: colors.ink, fontSize: 16, fontWeight: "900" },
  orderAmount: { color: colors.ink, fontSize: 15, fontWeight: "900" },
  pickupName: { color: colors.ink, fontWeight: "800" },
  addressLine: { color: colors.muted, fontSize: 12, fontWeight: "600" },
  inlineMeta: { flexDirection: "row", alignItems: "center", gap: 6 },
  metaTiny: { color: "#536176", fontSize: 12, fontWeight: "700" },
  metaDot: { color: colors.red, fontWeight: "900" },
  acceptMini: { marginTop: 5, height: 34, borderRadius: 8, backgroundColor: colors.red, alignItems: "center", justifyContent: "center" },
  acceptMiniText: { color: "#fff", fontWeight: "900" },
  statusChip: { alignSelf: "flex-start", marginTop: 5, paddingHorizontal: 9, height: 26, borderRadius: 8, flexDirection: "row", alignItems: "center", gap: 5, backgroundColor: "#ecfff4" },
  statusChipText: { color: "#0d8a4b", fontSize: 12, fontWeight: "900" },

  detailScroll: { padding: 14, gap: 12, paddingBottom: 32 },
  detailsCard: { backgroundColor: "#fff", borderRadius: 8, padding: 14, gap: 14, borderWidth: 1, borderColor: colors.line },
  summaryRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  sectionHeading: { color: colors.ink, fontSize: 14, fontWeight: "900" },
  infoBlock: { flexDirection: "row", alignItems: "center", gap: 10 },
  infoTitle: { color: colors.ink, fontSize: 15, fontWeight: "900" },
  infoName: { color: colors.ink, fontSize: 15, fontWeight: "900" },
  contactBtns: { flexDirection: "row", gap: 6 },
  contactBtn: { width: 36, height: 36, borderRadius: 8, alignItems: "center", justifyContent: "center", backgroundColor: "#eafff1", borderWidth: 1, borderColor: "#c5f4d8" },
  itemRow: { minHeight: 26, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  itemName: { flex: 1, color: "#536176", fontWeight: "700" },
  itemPrice: { color: "#7a89a0", fontWeight: "800" },
  totalRow: { paddingTop: 8, borderTopWidth: 1, borderTopColor: "#edf2f9", flexDirection: "row", justifyContent: "space-between" },
  totalLabel: { color: colors.ink, fontWeight: "900" },
  totalValue: { color: colors.ink, fontWeight: "900" },

  timeline: { marginTop: 6, flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 4 },
  timelineItem: { flex: 1, alignItems: "center", gap: 5 },
  timelineDot: { width: 28, height: 28, borderRadius: 14, backgroundColor: "#cbd5e1", alignItems: "center", justifyContent: "center" },
  timelineDotDone: { backgroundColor: colors.green },
  timelineLabel: { color: "#8190a7", fontSize: 10, fontWeight: "800", textAlign: "center" },
  timelineLabelDone: { color: colors.ink },

  modalBackdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(15,23,42,0.45)" },
  modalCard: { padding: 18, gap: 12, borderTopLeftRadius: 20, borderTopRightRadius: 20, backgroundColor: "#fff" },
  modalTitle: { color: colors.ink, fontSize: 22, fontWeight: "900" },
  modalInput: { minHeight: 52, paddingHorizontal: 14, borderRadius: 8, borderWidth: 1, borderColor: "#d9e2ef", color: colors.ink, fontWeight: "700" },
  textArea: { minHeight: 92, paddingTop: 14, textAlignVertical: "top" },
  proofPreview: { width: "100%", height: 140, borderRadius: 8, backgroundColor: "#edf2f9" },

  bottomTabs: { position: "absolute", left: 0, right: 0, bottom: 0, height: 78, paddingTop: 8, paddingBottom: 8, borderTopWidth: 1, borderTopColor: colors.line, backgroundColor: "#fff", flexDirection: "row" },
  bottomTab: { flex: 1, alignItems: "center", justifyContent: "center", gap: 3 },
  bottomLabel: { color: "#1f3157", fontSize: 11, fontWeight: "800" },
  bottomLabelActive: { color: colors.red }
});
